-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.6.16 - MySQL Community Server (GPL)
-- Server OS:                    Win32
-- HeidiSQL version:             7.0.0.4053
-- Date/time:                    2014-11-04 21:29:48
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET FOREIGN_KEY_CHECKS=0 */;

-- Dumping structure for table servix_db.servicios
DROP TABLE IF EXISTS `servicios`;
CREATE TABLE IF NOT EXISTS `servicios` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `id_categorias` int(11) unsigned NOT NULL,
  `id_localidades` int(11) unsigned NOT NULL,
  `titulo` varchar(45) NOT NULL,
  `descripcion` text NOT NULL,
  `foto` varchar(45) DEFAULT NULL,
  `url_web` varchar(45) DEFAULT NULL,
  `direccion` varchar(250) NOT NULL,
  `telefono` varchar(45) DEFAULT NULL,
  `latitud` longtext NOT NULL,
  `longitud` longtext NOT NULL,
  PRIMARY KEY (`id`),
  KEY `id_localidades` (`id_localidades`),
  KEY `id_categorias` (`id_categorias`),
  CONSTRAINT `servicios_ibfk_1` FOREIGN KEY (`id_localidades`) REFERENCES `localidades` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `servicios_ibfk_2` FOREIGN KEY (`id_categorias`) REFERENCES `categorias` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=525 DEFAULT CHARSET=latin1;

-- Dumping data for table servix_db.servicios: ~52 rows (approximately)
DELETE FROM `servicios`;
/*!40000 ALTER TABLE `servicios` DISABLE KEYS */;
INSERT INTO `servicios` (`id`, `id_categorias`, `id_localidades`, `titulo`, `descripcion`, `foto`, `url_web`, `direccion`, `telefono`, `latitud`, `longitud`) VALUES
	(3, 1, 54, 'trousers public wide stick keep', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', '100/100', 'http://google.com/', '{alguna calle 2145}', '637-888-9670', '10', '260'),
	(30, 2, 16, 'degree', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'side present side west root common stocking h', 'kick moon good property road sound short poli', '3609 State Loop 1', '355-908-8964', '124930292', '792375873'),
	(47, 24, 19, 'cotton nail river', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'some effect stitch rhythm broken song kind do', 'sand blow with high division fat together min', '3753 State Hwy 70G Bus', '267-582-4736', '630076610', '182578414'),
	(57, 12, 48, 'porter come side', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'as hat heart long clock crime apple then enou', 'harbour lip all drop than rain news cork song', '796 State Loop 458', '554-859-2069', '411472431', '55321903'),
	(64, 36, 82, 'sock stiff fight', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'lip train son with because harmony dirty mass', 'bottle brick present belief seat week country', '34305 E Hurst', '848-067-5338', '770665544', '733742221'),
	(67, 10, 67, 'love through', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'print detail thing change whistle harbour at ', 'now shelf balance example apparatus move whil', '735 2nd St', '710-204-3126', '471541499', '618210106'),
	(74, 12, 87, 'knee take death loose', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'wash motion spade hook metal religion summer ', 'operation food answer burn angry pencil card ', '162 Eldorado Pkwy', '678-162-9399', '415391085', '771374111'),
	(105, 6, 33, 'public', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'tray mountain cook complex open verse drawer ', 'attack cause house left silver look dependent', '2594 Beltway 8', '210-542-3199', '191605195', '528202241'),
	(126, 31, 3, 'waiting', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'tomorrow breath bridge open match bad balance', 'join blood print frame any boy little blood s', '7830 FM 1191', '613-335-7907', '446014627', '18062313'),
	(137, 18, 17, 'married till conscious', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'cheap physical coat lead cry hat rail stateme', 'sort sock silk broken brass any destruction l', '81 S State Hwy 18', '847-678-2514', '335334585', '177533826'),
	(138, 3, 76, 'silk not I', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'crack see verse tooth meat cart value complet', 'muscle floor woman red table waste country po', '93689 N State Hwy 79', '844-775-5793', '496311929', '228784283'),
	(147, 28, 28, 'pleasure music table act', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'tired steel comfort chin back simple stone ta', 'stocking plate summer destruction twist fowl ', '45767 US Hwy 90U Bus', '606-845-1455', '371332870', '191471041'),
	(193, 21, 12, 'now angle', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'ticket very fixed watch grip mother necessary', 'sort fear poor committee level probable ficti', '27697 US Hwy 81D Bus', '145-690-6530', '326322070', '216826337'),
	(204, 12, 74, 'tray line', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'society wide second test clean cruel very orn', 'jump condition powder tree up regular thumb b', '49777 Doak St', '362-147-9691', '379852742', '11069465'),
	(208, 22, 36, 'Herreria los hermanos', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'statement writing space form will complete na', 'price field ball foolish expert poison comb s', '68 E San Antonio St', '103-513-0952', '-38.7751423', '-62.1179636'),
	(226, 8, 54, 'over thin root learning', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'fire such news decision near account line pro', 'arch coal twist pin milk till brain kind blue', '5068 FM 852', '186-704-1261', '698183890', '671562056'),
	(244, 37, 64, 'basin', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'credit canvas hospital cold whistle rest moon', 'low order room apparatus complete crack level', '628 US Hwy 259', '581-510-7535', '340245738', '217866679'),
	(262, 3, 58, 'night', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'station kiss through yellow brush language ha', 'increase east bridge development grass drawer', '630 Byrd Ave', '650-850-9951', '119930610', '183885541'),
	(329, 31, 95, 'different', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'hard regular near name south left put time ab', 'metal coat flame organizatio where self sad s', '30038 N Upshaw Blvd', '818-437-4339', '725429730', '633284882'),
	(334, 18, 3, 'impulse potato slow', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'clear bit request bell healthy he balance sou', 'summer reward discovery fruit cushion fact ey', '96 Carolina St', '280-254-8069', '636235724', '730619451'),
	(349, 15, 29, 'doubt bag', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'current breath drawer hollow dust circle comb', 'balance monkey low line cup news cover wool i', '62 FM 1244 E', '902-629-0288', '766668750', '686953936'),
	(384, 10, 35, 'smell', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'mind kick hand whistle thought plant rain spe', 'certain prison slope finger toe leg plant cup', '33 W Dale St', '331-075-2690', '472525998', '506984472'),
	(495, 35, 86, 'give', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'dress give shut baby full year ring expert wa', 'linen memory school operation ever as brush a', '63982 Western Ave', '709-851-2282', '779646299', '254414507'),
	(496, 17, 24, 'name observation', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'punishment material level beautiful table cha', 'bed seem slip history dear smooth support wav', '45 Uvalde Rd', '616-867-3710', '218239622', '191952107'),
	(497, 25, 61, 'fertile', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'thought experience before memory wave train m', 'farm grass button eye paste feather company f', '65698 S Getty St', '433-501-2199', '294032683', '129149595'),
	(498, 26, 33, 'military leather oven list', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'among middle then loose watch wise purpose di', 'married division slope book stitch roll mount', '863 S US Hwy 287 Nb', '633-371-2190', '778628275', '101464927'),
	(499, 15, 83, 'serious direction', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'competition kick vessel foolish art colour ta', 'opinion cheese cork seem hole week snow curta', '862 W Center Ave', '570-182-5396', '178322163', '440931198'),
	(500, 28, 15, 'military needle', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'degree grain lock bread map floor join idea r', 'take observation pot summer face manager not ', '93442 Salinas Ave', '664-971-4876', '307077067', '629452623'),
	(501, 13, 24, 'brain', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'before across condition bird nation wax baske', 'bright leaf leg loud opposite pin expert wine', '4937 Commerce St', '974-691-6149', '700771044', '198657393'),
	(502, 22, 76, 'Aceros Gongal', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'room secretary plant false help writing accou', 'town dark pipe polish brother way false shelf', 'Calle 27 al 1359', '619-493-3068', '-36.4827107', '-56.7078295'),
	(503, 35, 6, 'lock that ink', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'money small reason hat rain hat other door il', 'unit relation print bed pump business fat thu', '7863 State Hwy 289 Bus', '247-145-0960', '346658131', '517105212'),
	(504, 13, 4, 'death', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'harbour door house even body shake ornament w', 'up feeling who library hour able feeble offer', '902 Spr 231', '968-141-8449', '642806783', '479970430'),
	(505, 38, 1, 'paint', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'unit smash take cheese good reward key flat t', 'chemical damage quick than expansion green hi', '159 State Hwy 65', '183-342-1237', '157405003', '480807690'),
	(506, 10, 91, 'reason', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'leaf seem desire smoke competition cook milk ', 'again wax yesterday past kiss voice approval ', '4281 State Hwy 37 Alt', '732-782-3997', '298413536', '353937012'),
	(507, 19, 52, 'system hand sound', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'purpose cat house edge doubt than enough ever', 'very air bed wine nerve public swim material ', '56 Sr348', '672-183-8977', '76627760', '201219738'),
	(508, 10, 87, 'curtain false parcel late', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'danger representat as dust for company silver', 'experience come oven attempt attraction feath', '4664 Amber', '761-350-5185', '89855551', '239518099'),
	(509, 15, 78, 'cheese then addition', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'unit stocking month bitter some stitch hope p', 'shut by money comb store fire voice request m', '9478 State Loop 564', '299-167-4105', '58303606', '771837626'),
	(510, 1, 29, 'round bath chance necessary', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'dependent love sense old crack protest father', 'stage box hanging smoke and growth taste writ', '5792 Roland Ave', '486-137-6548', '416539072', '665122970'),
	(511, 22, 9, 'Rejas y portones Juan Carlos', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'crush true off cruel error liquid tooth late ', 'throat value current number daughter adjustme', '21 FM 487', '382-727-1001', '-36.7749285', '-59.8526113'),
	(512, 17, 56, 'wet horn attraction', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'porter expansion pain same digestion second e', 'branch ice wire exchange linen tired school w', '51 Cbd-Fair Park Link', '355-216-7347', '633422434', '353872004'),
	(513, 26, 56, 'oven smooth', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'equal monkey against coat or go bright appara', 'quiet competition run existence arm mind wood', '7550 S US Hwy 287', '786-536-4431', '268897645', '612829510'),
	(514, 37, 11, 'form square', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'talk card effect money yellow boy limit all a', 'do protest cotton mist please increase almost', '293 SE Loop 281', '194-084-5288', '595874535', '153275065'),
	(515, 19, 87, 'blade smash sound certain', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'expansion match trouble burst wound old grain', 'have solid cup harmony food wing down young l', '515 S Smith Ave', '690-469-6550', '657972316', '761113410'),
	(516, 30, 3, 'yellow butter fertile society', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'linen writing very stretch conscious strange ', 'with flight love basket send middle low bed n', '232 E Leona St', '748-931-5897', '379126042', '321301679'),
	(517, 4, 50, 'net middle comfort', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'serious bell fixed narrow steam substance use', 'bag effect digestion store month with coat co', '18 Hwy 67 E', '603-620-3353', '505777127', '116113709'),
	(518, 36, 41, 'thumb drink brass', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'fold north feeble expert scale stomach use or', 'let theory cook discussion dress impulse west', '90 W 6th St', '522-558-8679', '267337458', '652185998'),
	(519, 34, 56, 'horn discovery pain', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'bridge road after loud false have burn pull a', 'love theory wave fight bridge bell do unit fe', '20010 Morelos Ave', '193-003-6582', '217007333', '522109329'),
	(520, 24, 58, 'polish free', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'edge wound record knot humour drop drain shor', 'place wind go insurance cause cart operation ', '2695 NW Loop 564', '275-423-7021', '736060986', '123638337'),
	(521, 22, 76, 'Aceros de importación', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'room secretary plant false help writing accou', 'town dark pipe polish brother way false shelf', 'Calle 27 al 1359', '619-493-3068', '-36.4826107', '-56.7076295'),
	(522, 22, 36, 'Herreria los primos', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'statement writing space form will complete na', 'price field ball foolish expert poison comb s', '68 E San Antonio St', '103-513-0952', '-38.7651423', '-62.1279636'),
	(523, 22, 9, 'Herreria de caballos', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'crush true off cruel error liquid tooth late ', 'throat value current number daughter adjustme', '21 FM 487', '382-727-1001', '-36.7769285', '-59.8586113'),
	(524, 22, 9, 'Herreria de caballos 2', 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años', 'crush true off cruel error liquid tooth late ', 'throat value current number daughter adjustme', '21 FM 487', '382-727-1001', '-36.7765285', '-59.8546113');
/*!40000 ALTER TABLE `servicios` ENABLE KEYS */;
/*!40014 SET FOREIGN_KEY_CHECKS=1 */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
